const TagTypes = {
  Profile: "Profile",
  Auth: "Auth",
  User: "User",
  Quote: "Quote",
  ServiceCall: "ServiceCall",
  EvCharger: "EvCharger",
  PanelUpgrade: "PanelUpgrade",
  Remodeling: "Remodeling",
  AccessoryBuilding: "AccessoryBuilding",
  HotTub: "HotTub",
  DockPower: "DockPower",
  Electric: "Electric",
  Generator: "Generator",
  NewConstruction: "NewConstruction",
  HomeSurgeProtection: "HomeSurgeProtection",
  Starlink: "Starlink",
  DedicatedCircuit: "DedicatedCircuit",
  Lighting: "Lighting",
  ExhaustFan: "ExhaustFan",
  Outlet: "Outlet",
  Switches: "Switches",
  CeilingFan: "CeilingFan",
  QUOTES: "Quotes",
  Draft: "Draft",
  Partner: "Partner",
  FAQ: "FAQ",
  AboutUs: "AboutUs",
  Terms: "Terms",
} as const;

export default TagTypes;
